### ISSUE TITLE
Data Structure & Algorithms

### ISSUE THREAD

**Issue by AllStackDev1** [developercirclesaccra/The-Tech-Demystify#4]
Been a software developer is not all about writing codes, there are lot of things involve to make sure your code which overall is your application uses the best possible space and time complexity and algorithms making your application run fast. 
Type of data structures and algorithms.
Intro into Big O (Time and Space complexity)
Big companies look out for this. WHY?

**Comment by Devoteng1** [comment]
Great. Looking forward for this
